# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/signupdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignUpDialog(object):
    def setupUi(self, SignUpDialog):
        SignUpDialog.setObjectName("SignUpDialog")
        SignUpDialog.resize(240, 320)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SignUpDialog.sizePolicy().hasHeightForWidth())
        SignUpDialog.setSizePolicy(sizePolicy)
        SignUpDialog.setMinimumSize(QtCore.QSize(240, 320))
        SignUpDialog.setMaximumSize(QtCore.QSize(240, 320))
        self.verticalLayout = QtWidgets.QVBoxLayout(SignUpDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_username = QtWidgets.QLabel(SignUpDialog)
        self.label_username.setObjectName("label_username")
        self.verticalLayout.addWidget(self.label_username)
        self.lineEdit_username = QtWidgets.QLineEdit(SignUpDialog)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.verticalLayout.addWidget(self.lineEdit_username)
        self.label_email = QtWidgets.QLabel(SignUpDialog)
        self.label_email.setObjectName("label_email")
        self.verticalLayout.addWidget(self.label_email)
        self.lineEdit_email = QtWidgets.QLineEdit(SignUpDialog)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.verticalLayout.addWidget(self.lineEdit_email)
        self.label_password = QtWidgets.QLabel(SignUpDialog)
        self.label_password.setObjectName("label_password")
        self.verticalLayout.addWidget(self.label_password)
        self.lineEdit_password = QtWidgets.QLineEdit(SignUpDialog)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout.addWidget(self.lineEdit_password)
        self.label_confirm_password = QtWidgets.QLabel(SignUpDialog)
        self.label_confirm_password.setObjectName("label_confirm_password")
        self.verticalLayout.addWidget(self.label_confirm_password)
        self.lineEdit_confirm_password = QtWidgets.QLineEdit(SignUpDialog)
        self.lineEdit_confirm_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_confirm_password.setObjectName("lineEdit_confirm_password")
        self.verticalLayout.addWidget(self.lineEdit_confirm_password)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(SignUpDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SignUpDialog)
        self.buttonBox.rejected.connect(SignUpDialog.reject)
        self.buttonBox.accepted.connect(SignUpDialog.accept)
        QtCore.QMetaObject.connectSlotsByName(SignUpDialog)

    def retranslateUi(self, SignUpDialog):
        _translate = QtCore.QCoreApplication.translate
        SignUpDialog.setWindowTitle(_translate("SignUpDialog", "SafeWaze Signup"))
        self.label_username.setText(_translate("SignUpDialog", "Username"))
        self.label_email.setText(_translate("SignUpDialog", "E-Mail Address"))
        self.label_password.setText(_translate("SignUpDialog", "Password"))
        self.label_confirm_password.setText(_translate("SignUpDialog", "Confirm Password"))
