# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import QLCDNumber, QPushButton
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dashboard(object):
    def setupUi(self, Dashboard):
        Dashboard.setObjectName("Dashboard")
        Dashboard.resize(900, 700)
        Dashboard.setMinimumSize(QtCore.QSize(900, 700))
        Dashboard.setStyleSheet("#centralwidget {background-color: rgb(131,34,65);}")
        self.centralwidget = QtWidgets.QWidget(Dashboard)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet("background-color: rgb(215,210,203);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.vbox_tab_1 = QtWidgets.QVBoxLayout()
        self.vbox_tab_1.setObjectName("vbox_tab_1")
        self.hbox_info = QtWidgets.QHBoxLayout()
        self.hbox_info.setSpacing(6)
        self.hbox_info.setObjectName("hbox_info")
        self.widget_left = QtWidgets.QWidget(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_left.sizePolicy().hasHeightForWidth())
        self.widget_left.setSizePolicy(sizePolicy)
        self.widget_left.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_left.setStyleSheet("background-color: rgb(252, 175, 62);")
        self.widget_left.setObjectName("widget_left")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_left)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.risk_barometer = QtWidgets.QProgressBar(self.widget_left)
        self.risk_barometer.setStyleSheet("QProgressBar {\n"
"border-image: url(:/Gauge/Resources/Risk-Gradient/V2/gradient-v2-600x600.png);\n"
"border-radius: 12px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"stop: 0 #fff\n"
"stop: 0.4999 #eee\n"
"stop: 0.5 #ddd,\n"
"stop: 1 #eee);\n"
"}")
        self.risk_barometer.setProperty("value", 80)
        self.risk_barometer.setTextVisible(False)
        self.risk_barometer.setOrientation(QtCore.Qt.Vertical)
        self.risk_barometer.setInvertedAppearance(True)
        self.risk_barometer.setObjectName("risk_barometer")
        self.horizontalLayout_4.addWidget(self.risk_barometer)
        self.lcdNumber_risk = QtWidgets.QLCDNumber(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_risk.sizePolicy().hasHeightForWidth())
        self.lcdNumber_risk.setSizePolicy(sizePolicy)
        self.lcdNumber_risk.setMinimumSize(QtCore.QSize(60, 0))
        self.lcdNumber_risk.setDigitCount(3)
        self.lcdNumber_risk.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_risk.setProperty("intValue", 0)
        self.lcdNumber_risk.setObjectName("lcdNumber_risk")
        self.horizontalLayout_4.addWidget(self.lcdNumber_risk)
        self.vbox_risk_factors = QtWidgets.QVBoxLayout()
        self.vbox_risk_factors.setObjectName("vbox_risk_factors")
        self.label = QtWidgets.QLabel(self.widget_left)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.vbox_risk_factors.addWidget(self.label)
        self.label_4 = QtWidgets.QLabel(self.widget_left)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.vbox_risk_factors.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget_left)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.vbox_risk_factors.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget_left)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.vbox_risk_factors.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.widget_left)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.vbox_risk_factors.addWidget(self.label_7)
        self.horizontalLayout_4.addLayout(self.vbox_risk_factors)
        self.hbox_info.addWidget(self.widget_left)
        self.widget_rss = QtWidgets.QWidget(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_rss.sizePolicy().hasHeightForWidth())
        self.widget_rss.setSizePolicy(sizePolicy)
        self.widget_rss.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_rss.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_rss.setObjectName("widget_rss")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_rss)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_rss_header = QtWidgets.QLabel(self.widget_rss)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_rss_header.sizePolicy().hasHeightForWidth())
        self.label_rss_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_rss_header.setFont(font)
        self.label_rss_header.setObjectName("label_rss_header")
        self.verticalLayout_2.addWidget(self.label_rss_header)
        self.line = QtWidgets.QFrame(self.widget_rss)
        self.line.setStyleSheet("background-color: transparent;")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.label_rss_title = QtWidgets.QLabel(self.widget_rss)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_rss_title.setFont(font)
        self.label_rss_title.setStyleSheet("background-color: transparent;")
        self.label_rss_title.setWordWrap(True)
        self.label_rss_title.setOpenExternalLinks(True)
        self.label_rss_title.setObjectName("label_rss_title")
        self.verticalLayout_2.addWidget(self.label_rss_title)
        self.label_rss_date = QtWidgets.QLabel(self.widget_rss)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_rss_date.setFont(font)
        self.label_rss_date.setObjectName("label_rss_date")
        self.verticalLayout_2.addWidget(self.label_rss_date)
        self.textBrowser_summary = QtWidgets.QTextBrowser(self.widget_rss)
        self.textBrowser_summary.setFrameShape(QtWidgets.QFrame.Box)
        self.textBrowser_summary.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_summary.setOpenExternalLinks(True)
        self.textBrowser_summary.setObjectName("textBrowser_summary")
        self.verticalLayout_2.addWidget(self.textBrowser_summary)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.radioButton_1 = QtWidgets.QRadioButton(self.widget_rss)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_1.sizePolicy().hasHeightForWidth())
        self.radioButton_1.setSizePolicy(sizePolicy)
        self.radioButton_1.setMinimumSize(QtCore.QSize(20, 0))
        self.radioButton_1.setText("")
        self.radioButton_1.setChecked(True)
        self.radioButton_1.setObjectName("radioButton_1")
        self.horizontalLayout.addWidget(self.radioButton_1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget_rss)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_2.sizePolicy().hasHeightForWidth())
        self.radioButton_2.setSizePolicy(sizePolicy)
        self.radioButton_2.setMinimumSize(QtCore.QSize(20, 0))
        self.radioButton_2.setText("")
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.widget_rss)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_3.sizePolicy().hasHeightForWidth())
        self.radioButton_3.setSizePolicy(sizePolicy)
        self.radioButton_3.setMinimumSize(QtCore.QSize(20, 0))
        self.radioButton_3.setText("")
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.widget_rss)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_4.sizePolicy().hasHeightForWidth())
        self.radioButton_4.setSizePolicy(sizePolicy)
        self.radioButton_4.setMinimumSize(QtCore.QSize(20, 0))
        self.radioButton_4.setText("")
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.widget_rss)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_5.sizePolicy().hasHeightForWidth())
        self.radioButton_5.setSizePolicy(sizePolicy)
        self.radioButton_5.setMinimumSize(QtCore.QSize(20, 0))
        self.radioButton_5.setText("")
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.widget_rss)
        self.radioButton_6.setMinimumSize(QtCore.QSize(20, 0))
        self.radioButton_6.setText("")
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout.addWidget(self.radioButton_6)
        self.radioButton_7 = QtWidgets.QRadioButton(self.widget_rss)
        self.radioButton_7.setMinimumSize(QtCore.QSize(20, 0))
        self.radioButton_7.setText("")
        self.radioButton_7.setObjectName("radioButton_7")
        self.horizontalLayout.addWidget(self.radioButton_7)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.hbox_info.addWidget(self.widget_rss)
        self.vbox_tab_1.addLayout(self.hbox_info)
        self.frame_graph = QtWidgets.QFrame(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_graph.sizePolicy().hasHeightForWidth())
        self.frame_graph.setSizePolicy(sizePolicy)
        self.frame_graph.setMinimumSize(QtCore.QSize(758, 325))
        self.frame_graph.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_graph.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph.setObjectName("frame_graph")
        self.label_8 = QtWidgets.QLabel(self.frame_graph)
        self.label_8.setGeometry(QtCore.QRect(80, 40, 251, 16))
        self.label_8.setObjectName("label_8")
        self.comboBox_4 = QtWidgets.QComboBox(self.frame_graph)
        self.comboBox_4.setGeometry(QtCore.QRect(80, 70, 141, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_2 = QtWidgets.QLabel(self.frame_graph)
        self.label_2.setGeometry(QtCore.QRect(80, 110, 261, 20))
        self.label_2.setObjectName("label_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_graph)
        self.comboBox_2.setGeometry(QtCore.QRect(80, 140, 141, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_3 = QtWidgets.QLabel(self.frame_graph)
        self.label_3.setGeometry(QtCore.QRect(520, 40, 251, 16))
        self.label_3.setObjectName("label_3")
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_graph)
        self.comboBox_3.setGeometry(QtCore.QRect(520, 70, 141, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_9 = QtWidgets.QLabel(self.frame_graph)
        self.label_9.setGeometry(QtCore.QRect(520, 110, 271, 20))
        self.label_9.setObjectName("label_9")
        self.comboBox = QtWidgets.QComboBox(self.frame_graph)
        self.comboBox.setGeometry(QtCore.QRect(520, 140, 141, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.submit = QtWidgets.QPushButton(self.frame_graph)
        self.submit.setGeometry(QtCore.QRect(360, 210, 121, 31))
        self.submit.setObjectName("submit")


        self.submit.clicked.connect(self.pressed)
        #self.lcdNumber_risk.setProperty("intValue", 100)
        self.submit.clicked.connect(self.updateLCD)

        self.vbox_tab_1.addWidget(self.frame_graph)
        self.verticalLayout_6.addLayout(self.vbox_tab_1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        Dashboard.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Dashboard)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 26))
        self.menubar.setObjectName("menubar")
        Dashboard.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Dashboard)
        self.statusbar.setObjectName("statusbar")
        Dashboard.setStatusBar(self.statusbar)

        self.retranslateUi(Dashboard)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dashboard)

    def retranslateUi(self, Dashboard):
        _translate = QtCore.QCoreApplication.translate
        Dashboard.setWindowTitle(_translate("Dashboard", "SafeWaze Dashboard"))
        self.label.setText(_translate("Dashboard", "Risk Factor"))
        self.label_4.setText(_translate("Dashboard", "Risk Factor"))
        self.label_5.setText(_translate("Dashboard", "Risk Factor"))
        self.label_6.setText(_translate("Dashboard", "Risk Factor"))
        self.label_7.setText(_translate("Dashboard", "Risk Factor"))
        self.label_rss_header.setText(_translate("Dashboard", "Recent CDC COVID-19 Updates"))
        self.label_rss_title.setText(_translate("Dashboard", "Article Title"))
        self.label_rss_date.setText(_translate("Dashboard", "Date"))
        self.label_8.setText(_translate("Dashboard", "Choose the type of place you will be visiting"))
        self.comboBox_4.setItemText(0, _translate("Dashboard", "convenience store"))
        self.comboBox_4.setItemText(1, _translate("Dashboard", "Supermarket"))
        self.comboBox_4.setItemText(2, _translate("Dashboard", "Barber Shop"))
        self.comboBox_4.setItemText(3, _translate("Dashboard", "Restaurant / Bar"))
        self.comboBox_4.setItemText(4, _translate("Dashboard", "Playground"))
        self.comboBox_4.setItemText(5, _translate("Dashboard", "movie theatre"))
        self.comboBox_4.setItemText(6, _translate("Dashboard", "Gym"))
        self.comboBox_4.setItemText(7, _translate("Dashboard", "Other"))
        self.label_2.setText(_translate("Dashboard", "Will everyone be practicing social distancing?"))
        self.comboBox_2.setItemText(0, _translate("Dashboard", "Yes"))
        self.comboBox_2.setItemText(1, _translate("Dashboard", "No"))
        self.comboBox_2.setItemText(2, _translate("Dashboard", "Not all"))
        self.label_3.setText(_translate("Dashboard", "Will everyone be wearing a mask or shield?"))
        self.comboBox_3.setItemText(0, _translate("Dashboard", "Yes"))
        self.comboBox_3.setItemText(1, _translate("Dashboard", "No"))
        self.comboBox_3.setItemText(2, _translate("Dashboard", "Not all"))
        self.label_9.setText(_translate("Dashboard", "How many people will you be interacting with?"))
        self.comboBox.setItemText(0, _translate("Dashboard", "None"))
        self.comboBox.setItemText(1, _translate("Dashboard", "1"))
        self.comboBox.setItemText(2, _translate("Dashboard", "2"))
        self.comboBox.setItemText(3, _translate("Dashboard", "3"))
        self.comboBox.setItemText(4, _translate("Dashboard", "4"))
        self.comboBox.setItemText(5, _translate("Dashboard", "5 - 9"))
        self.comboBox.setItemText(6, _translate("Dashboard", "10 or more"))
        self.submit.setText(_translate("Dashboard", "SUBMIT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Dashboard", "Info"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dashboard", "Maps"))


    def pressed(self):

        index_box0 = self.comboBox.currentIndex()
        index_box2 = self.comboBox_2.currentIndex()
        index_box3 = self.comboBox_3.currentIndex()
        index_box4 = self.comboBox_4.currentIndex()

        #  print('Number of people interacting:', index_box0)  #index people interacting
        #  print('are you practicing social distancing:', index_box2)  #social distancing or not
        #  print('are you wearing mask or shield:', index_box3)  #index mask or shield
        #  print('type of place:', index_box4)  #index type of place
        # type of place visiting- user input.
        # indoor or outdoor - depending on place visiting.
        # amount of time spent - based on place visiting.
        # num of people interacting with - user input
        # social distancing  - user input
        # masks/shield - user input
        #type of place

        if index_box4 == 0:
            risk_place = 1
            time_spent = 1
        elif index_box4 == 1:
            risk_place = 2
            time_spent = 3
        elif index_box4 == 2:
            risk_place = 4
            time_spent = 3
        elif index_box4 == 3:
            risk_place = 9
            time_spent = 4
        elif index_box4 == 4:
            risk_place = 6
            time_spent =4
        elif index_box4 == 5:
            risk_place = 10
            time_spent = 3
        elif index_box4 == 6:
            risk_place = 9
            time_spent = 2
        else:
            risk_place = 3   # other place.
            time_spent = 3

        #numberofpeople interacted with
        if index_box0 == 0:
            risk_person = 0
        elif index_box0 == 1:
            risk_person = 1
        elif index_box0 == 2:
            risk_person = 3
        elif index_box0 == 3:
            risk_person = 5
        elif index_box0 == 4:
            risk_person = 7
        elif index_box0 == 5:
            risk_person = 9
        else:
            risk_person = 18

         #social distancing?
        if index_box2 == 0:
            risk_multiplier = 0.8
        elif index_box2 == 1:
            risk_multiplier = 1.5
        else:
            risk_multiplier = 1

        #mask or shield
        if index_box3 == 0:
            risk_add = 1
        elif index_box3 == 1:
            risk_add = 12
        else:
            risk_add = (risk_place * risk_multiplier) + (risk_person/2)

        risk_final = risk_add + (risk_place*time_spent)/2 + risk_person + 28
        print("risk_add is: ", risk_add)
        print("risk_place is:", risk_place)
        print("time spent is:", time_spent)
        print("risk person is:", risk_person)
        print("Your final risk score is:", risk_final)

        return risk_final



    ##is this right?
    def updateLCD(self):
        self.lcdNumber_risk.display(self.pressed())
        bar_value = 100 - self.pressed()
        self.risk_barometer.setValue(bar_value)


import package.ui.resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dashboard = QtWidgets.QMainWindow()
    ui = Ui_Dashboard()
    ui.setupUi(Dashboard)
    Dashboard.show()
    sys.exit(app.exec_())
